USE NikamoozDB;
GO

DECLARE @VAR INT;
SET @VAR = 100;
GO

DECLARE @VAR INT = 100;
--SELECT @VAR;
PRINT @VAR;
GO

DECLARE @VAR1 INT, @VAR2 INT, @VAR3 DATE;
SELECT @VAR1 = 1000, @VAR2 = 2000, @VAR3 = GETDATE();
SELECT @VAR1, @VAR2, @VAR3;
GO

DECLARE @VAR1 INT, @VAR2 INT, @VAR3 DATE;
SET @VAR1 = 1000;
SET @VAR2 = 2000;
SET @VAR3 = GETDATE();
SELECT @VAR1, @VAR2, @VAR3;
GO

DECLARE @VAR1 INT, @VAR2 INT, @VAR3 DATE;
SELECT @VAR1 = 1000, @VAR2 = 2000, @VAR3 = GETDATE();
PRINT @VAR1;
PRINT @VAR2;
PRINT @VAR3;
GO

SELECT * FROM dbo.Employees;
GO

DECLARE @Family NVARCHAR(50);
SET @Family = 
	(
		SELECT LastName 
		FROM dbo.Employees 
			WHERE mgrid = 2);
PRINT @Family;
GO

DECLARE @Family NVARCHAR(50);
SELECT @Family = LastName FROM dbo.Employees
	WHERE mgrid = 2
PRINT @Family;
GO